Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.lwd.cleverrpm.app.aws.lambda.ReadingAwsLambda
      CodeUri: C:\development\get-reading-aws-lambda\GetReading
      Runtime: java11
      Architectures:
        - x86_64